### ISSUE TITLE
---

### ISSUE THREAD

**Issue by kek-dev** [cpz/Lost-Ark-SDK#2]
Привет, в рамках обучения реверсингу и с++ хочу реализовать какой-нибудь небольшой учебный проект, выбрал lost ark, наткнулся на твой sdk, можно ли с тобой связаться (discord / telegram) и позадавать несколько глупых вопросов? Если хочешь, то даже за небольшое денежное вознаграждение 

Спасибо

**Comment by cpz** [comment]
Привет!Напиши свою почту, я на неё дропну тг/диз.--Отправлено из мобильной Яндекс.Почты19.06.2020, 22:35, "Az Bik" <notifications@github.com>:
Привет, в рамках обучения реверсингу и с++ хочу реализовать какой-нибудь небольшой учебный проект, выбрал lost ark, наткнулся на твой sdk, можно ли с тобой связаться (discord / telegram) и позадавать несколько глупых вопросов? Если хочешь, то даже за небольшое денежное вознаграждение
Спасибо

**Comment by kek-dev** [comment]
azbik999@gmail.com

> Привет!Напиши свою почту, я на неё дропну тг/диз.--Отправлено из мобильной Яндекс.Почты19.06.2020, 22:35, "Az Bik" <notifications@github.com>: Привет, в рамках обучения реверсингу и с++ хочу реализовать какой-нибудь небольшой учебный проект, выбрал lost ark, наткнулся на твой sdk, можно ли с тобой связаться (discord / telegram) и позадавать несколько глупых вопросов? Если хочешь, то даже за небольшое денежное вознаграждение Спасибо —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
